name := "ml-algorithms-in-scala"
version := "0.0.1"
scalaVersion := "2.10.4"
//libraryDependencies += "org.apache.spark" %% "spark-core" % "1.2.0 "
libraryDependencies += "org.apache.spark" % "spark-core_2.10" % "1.2.0"
